# Generated by Django 5.0.6 on 2024-05-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_id_alter_coupon_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
