# Generated by Django 5.0.6 on 2024-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
